/**
 * GENERATED by `npm run art` from src/assets/art/parts/ — do not edit.
 *
 * The parts a gnome can be built from, by layer. Ids come from the
 * filenames, so adding a part is adding a file and re-running the generator.
 *
 * These ids are stored in `MatchRecord` and sent over the wire: REMOVING one
 * breaks games that used it, so retire a part by deleting its file only if no
 * saved game needs to replay.
 */

export const PART_IDS = {
  "weapon": [
    "axe",
    "broom",
    "pitchfork",
    "shovel",
    "staff"
  ],
  "base": [
    "gnome"
  ],
  "beard": [
    "braided",
    "bushy",
    "pointy",
    "stubble",
    "wild"
  ],
  "cap": [
    "bulbous",
    "droopy",
    "pointy",
    "tall",
    "wide"
  ],
  "accessory": [
    "none",
    "flower",
    "glasses",
    "lantern",
    "monocle",
    "pipe"
  ]
} as const;

/** Layers a player picks from, in the order the picker shows them. */
export const CHOOSABLE_LAYERS = ["weapon","beard","cap","accessory"] as const;

/** The id an optional layer uses for "wearing nothing". Never a file. */
export const NONE_ID = "none";

export type ChoosableLayer = (typeof CHOOSABLE_LAYERS)[number];
