/**
 * Compiles the ASCII sprites into `src/ui/appearance/spriteData.ts`.
 *
 * Run with `npm run art` after editing `sprites.mjs`. The output is generated
 * and checked in, so the app never parses ASCII at runtime and the build stays
 * a plain `tsc && vite build`.
 *
 * Why not PNGs, like the gardens: a team's colours are chosen at runtime and
 * applied to a five-step ramp, and an `<img>` cannot be palette-swapped —
 * CSS filters do hue rotation, not a per-step colour map. Each sprite becomes
 * one SVG path per ramp step instead, which `recolor.ts` fills with that
 * team's ramp and memoises into a single data URI.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { GRID, parse, RAMP, FIXED } from './pixel.mjs';
import * as SPRITES from './sprites.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, '..', '..', 'src', 'ui', 'appearance', 'spriteData.ts');

/** Char -> the key `recolor.ts` fills it with. Ramp steps are named; fixed colours are literal. */
const KEY = Object.fromEntries([
  ...Object.entries(RAMP).map(([ch]) => [ch, ch]),
  ...Object.entries(FIXED).filter(([, hex]) => hex !== null).map(([ch, hex]) => [ch, hex]),
]);

/**
 * One path per colour, built from horizontal runs. Merging a row of identical
 * pixels into a single rect keeps the generated file small enough to read.
 */
function toPaths(grid, byChar) {
  const runs = new Map();
  for (let y = 0; y < GRID; y++) {
    let x = 0;
    while (x < GRID) {
      const ch = byChar[y][x];
      if (ch === '.') { x++; continue; }
      let w = 1;
      while (x + w < GRID && byChar[y][x + w] === ch) w++;
      const key = KEY[ch];
      if (!runs.has(key)) runs.set(key, []);
      runs.get(key).push(`M${x} ${y}h${w}v1h-${w}z`);
      x += w;
    }
  }
  return Object.fromEntries([...runs].map(([k, v]) => [k, v.join('')]));
}

const out = {};
for (const [name, rows] of Object.entries(SPRITES)) {
  if (!Array.isArray(rows)) continue; // the CAPS/BEARDS/... index objects
  parse(rows, name); // validation only: throws on a bad grid or unknown char
  out[name] = toPaths(rows, rows.map((r) => [...r]));
}

const banner = `/**
 * GENERATED by \`npm run art\` from scripts/art/sprites.mjs — do not edit.
 *
 * Each sprite is a map from fill key to SVG path data on a ${GRID}x${GRID} viewBox.
 * A single-character key ('0'-'4') is a step of the recolourable ramp, darkest
 * to lightest; a '#rrggbb' key is a fixed colour that survives recolouring.
 */

/** The viewBox every sprite is drawn on. */
export const SPRITE_GRID = ${GRID};

/** Ramp step keys, darkest first. */
export const RAMP_KEYS = ['0', '1', '2', '3', '4'] as const;
export type RampKey = (typeof RAMP_KEYS)[number];

export type SpritePaths = Readonly<Record<string, string>>;

export const SPRITES: Readonly<Record<string, SpritePaths>> = ${JSON.stringify(out, null, 2)};
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, banner);
console.log(`wrote ${OUT} (${Object.keys(out).length} sprites, ${(banner.length / 1024).toFixed(1)} KiB)`);
