/**
 * GENERATED by `npm run art` from scripts/art/sprites.mjs — do not edit.
 *
 * Each sprite is a map from fill key to SVG path data on a 32x32 viewBox.
 * A single-character key ('0'-'4') is a step of the recolourable ramp, darkest
 * to lightest; a '#rrggbb' key is a fixed colour that survives recolouring.
 */

/** The viewBox every sprite is drawn on. */
export const SPRITE_GRID = 32;

/** Ramp step keys, darkest first. */
export const RAMP_KEYS = ['0', '1', '2', '3', '4'] as const;
export type RampKey = (typeof RAMP_KEYS)[number];

export type SpritePaths = Readonly<Record<string, string>>;

export const SPRITES: Readonly<Record<string, SpritePaths>> = {
  "ACC_LANTERN": {
    "0": "M5 15h2v1h-2zM4 16h1v1h-1zM7 16h1v1h-1zM3 17h6v1h-6zM3 18h1v1h-1zM8 18h1v1h-1zM3 19h1v1h-1zM8 19h1v1h-1zM3 20h1v1h-1zM8 20h1v1h-1zM3 21h6v1h-6z",
    "3": "M5 20h2v1h-2z",
    "4": "M4 18h4v1h-4zM4 19h4v1h-4zM4 20h1v1h-1zM7 20h1v1h-1z"
  },
  "ACC_MONOCLE": {
    "4": "M18 13h3v1h-3zM17 14h1v1h-1zM21 14h1v1h-1zM17 15h1v1h-1zM21 15h1v1h-1zM18 16h3v1h-3zM21 17h1v1h-1zM21 18h1v1h-1zM20 19h1v1h-1z"
  },
  "ACC_PIPE": {
    "0": "M4 22h3v1h-3zM3 23h1v1h-1zM6 23h1v1h-1zM3 24h1v1h-1zM6 24h1v1h-1zM3 25h1v1h-1zM6 25h1v1h-1zM4 26h2v1h-2z",
    "1": "M6 21h7v1h-7zM4 23h2v1h-2zM4 24h2v1h-2zM4 25h2v1h-2z"
  },
  "BASE": {
    "#241d16": "M12 8h8v1h-8zM10 9h1v1h-1zM21 9h1v1h-1zM9 10h1v1h-1zM22 10h1v1h-1zM8 11h1v1h-1zM23 11h1v1h-1zM8 12h1v1h-1zM23 12h1v1h-1zM8 13h1v1h-1zM23 13h1v1h-1zM8 14h1v1h-1zM23 14h1v1h-1zM8 15h1v1h-1zM23 15h1v1h-1zM8 16h1v1h-1zM23 16h1v1h-1zM8 17h1v1h-1zM23 17h1v1h-1zM8 18h1v1h-1zM23 18h1v1h-1zM8 19h1v1h-1zM23 19h1v1h-1zM8 20h1v1h-1zM23 20h1v1h-1zM8 21h1v1h-1zM23 21h1v1h-1zM9 22h1v1h-1zM22 22h1v1h-1zM10 23h1v1h-1zM21 23h1v1h-1zM12 24h8v1h-8z",
    "#e8c48f": "M11 9h10v1h-10zM11 10h10v1h-10zM11 11h10v1h-10zM11 12h10v1h-10zM11 13h10v1h-10zM9 14h14v1h-14zM9 15h2v1h-2zM14 15h4v1h-4zM21 15h2v1h-2zM9 16h14v1h-14zM9 17h6v1h-6zM17 17h6v1h-6zM9 18h6v1h-6zM17 18h6v1h-6zM9 19h14v1h-14zM9 20h14v1h-14zM9 21h14v1h-14zM10 22h12v1h-12zM11 23h10v1h-10z",
    "#f7dcb4": "M10 10h1v1h-1zM9 11h2v1h-2zM9 12h2v1h-2zM9 13h2v1h-2z",
    "#c99e63": "M21 10h1v1h-1zM21 11h2v1h-2zM21 12h2v1h-2zM21 13h2v1h-2zM15 17h2v1h-2zM15 18h2v1h-2z",
    "#ffffff": "M11 15h1v1h-1zM13 15h1v1h-1zM18 15h1v1h-1zM20 15h1v1h-1z",
    "#2a2118": "M12 15h1v1h-1zM19 15h1v1h-1z"
  },
  "BEARD_BUSHY": {
    "0": "M8 19h1v1h-1zM23 19h1v1h-1zM7 20h1v1h-1zM24 20h1v1h-1zM7 21h1v1h-1zM24 21h1v1h-1zM6 22h1v1h-1zM25 22h1v1h-1zM6 23h1v1h-1zM25 23h1v1h-1zM6 24h1v1h-1zM25 24h1v1h-1zM7 25h1v1h-1zM24 25h1v1h-1zM8 26h1v1h-1zM23 26h1v1h-1zM9 27h1v1h-1zM22 27h1v1h-1zM11 28h1v1h-1zM20 28h1v1h-1zM13 29h6v1h-6z",
    "1": "M16 21h8v1h-8zM16 22h9v1h-9zM7 23h18v1h-18zM7 24h18v1h-18zM8 25h16v1h-16zM9 26h14v1h-14zM10 27h12v1h-12zM12 28h8v1h-8z",
    "2": "M9 19h14v1h-14zM8 20h16v1h-16zM8 21h8v1h-8zM7 22h9v1h-9z"
  },
  "BEARD_POINTY": {
    "0": "M9 19h1v1h-1zM22 19h1v1h-1zM9 20h1v1h-1zM22 20h1v1h-1zM10 21h1v1h-1zM21 21h1v1h-1zM10 22h1v1h-1zM21 22h1v1h-1zM11 23h1v1h-1zM20 23h1v1h-1zM11 24h1v1h-1zM20 24h1v1h-1zM12 25h1v1h-1zM19 25h1v1h-1zM13 26h1v1h-1zM18 26h1v1h-1zM14 27h1v1h-1zM17 27h1v1h-1zM15 28h2v1h-2z",
    "1": "M11 22h10v1h-10zM12 23h8v1h-8zM12 24h8v1h-8zM13 25h6v1h-6zM14 26h4v1h-4zM15 27h2v1h-2z",
    "2": "M10 19h12v1h-12zM10 20h12v1h-12zM11 21h10v1h-10z"
  },
  "BEARD_WILD": {
    "0": "M8 19h1v1h-1zM23 19h1v1h-1zM6 20h1v1h-1zM25 20h1v1h-1zM5 21h1v1h-1zM26 21h1v1h-1zM5 22h1v1h-1zM26 22h1v1h-1zM5 23h1v1h-1zM26 23h1v1h-1zM6 24h1v1h-1zM25 24h1v1h-1zM6 25h1v1h-1zM14 25h2v1h-2zM25 25h1v1h-1zM6 26h1v1h-1zM12 26h1v1h-1zM15 26h1v1h-1zM23 26h1v1h-1zM7 27h1v1h-1zM11 27h1v1h-1zM15 27h1v1h-1zM20 27h1v1h-1zM8 28h2v1h-2zM13 28h1v1h-1zM16 28h1v1h-1z",
    "1": "M15 21h11v1h-11zM6 22h20v1h-20zM6 23h20v1h-20zM7 24h18v1h-18zM7 25h7v1h-7zM16 25h9v1h-9zM7 26h5v1h-5zM16 26h7v1h-7zM8 27h3v1h-3zM16 27h4v1h-4zM14 28h2v1h-2z",
    "2": "M9 19h14v1h-14zM7 20h18v1h-18zM6 21h9v1h-9z"
  },
  "CAP_BULBOUS": {
    "0": "M13 2h1v1h-1zM18 2h1v1h-1zM11 3h1v1h-1zM20 3h1v1h-1zM9 4h1v1h-1zM22 4h1v1h-1zM8 5h1v1h-1zM23 5h1v1h-1zM7 6h1v1h-1zM24 6h1v1h-1zM6 7h1v1h-1zM25 7h1v1h-1zM5 8h1v1h-1zM26 8h1v1h-1zM5 9h1v1h-1zM26 9h1v1h-1zM5 10h1v1h-1zM26 10h1v1h-1zM5 11h1v1h-1zM26 11h1v1h-1zM6 12h20v1h-20z",
    "1": "M21 4h1v1h-1zM22 5h1v1h-1zM23 6h1v1h-1zM23 7h2v1h-2zM24 8h2v1h-2zM24 9h2v1h-2zM24 10h2v1h-2zM6 11h20v1h-20z",
    "2": "M18 3h1v1h-1zM20 4h1v1h-1zM20 5h2v1h-2zM20 6h3v1h-3zM20 7h3v1h-3zM20 8h4v1h-4zM20 9h4v1h-4zM19 10h5v1h-5z",
    "3": "M14 2h4v1h-4zM12 3h6v1h-6zM19 3h1v1h-1zM10 4h5v1h-5zM17 4h3v1h-3zM9 5h4v1h-4zM16 5h4v1h-4zM8 6h5v1h-5zM16 6h4v1h-4zM7 7h6v1h-6zM16 7h4v1h-4zM6 8h7v1h-7zM16 8h4v1h-4zM6 9h8v1h-8zM16 9h4v1h-4zM6 10h13v1h-13z",
    "4": "M15 4h2v1h-2zM13 5h3v1h-3zM13 6h3v1h-3zM13 7h3v1h-3zM13 8h3v1h-3zM14 9h2v1h-2z"
  },
  "CAP_POINTY": {
    "0": "M15 1h2v1h-2zM14 2h1v1h-1zM17 2h1v1h-1zM13 3h1v1h-1zM18 3h1v1h-1zM12 4h1v1h-1zM19 4h1v1h-1zM11 5h1v1h-1zM20 5h1v1h-1zM11 6h1v1h-1zM20 6h1v1h-1zM10 7h1v1h-1zM21 7h1v1h-1zM9 8h1v1h-1zM22 8h1v1h-1zM8 9h1v1h-1zM23 9h1v1h-1zM7 10h1v1h-1zM24 10h1v1h-1zM6 11h1v1h-1zM25 11h1v1h-1zM6 12h1v1h-1zM25 12h1v1h-1zM7 13h18v1h-18z",
    "1": "M20 7h1v1h-1zM21 8h1v1h-1zM22 9h1v1h-1zM22 10h2v1h-2zM23 11h2v1h-2zM7 12h18v1h-18z",
    "2": "M17 4h1v1h-1zM17 5h2v1h-2zM18 6h2v1h-2zM18 7h2v1h-2zM18 8h3v1h-3zM19 9h3v1h-3zM19 10h3v1h-3zM19 11h4v1h-4z",
    "3": "M15 2h2v1h-2zM14 3h4v1h-4zM13 4h4v1h-4zM18 4h1v1h-1zM12 5h5v1h-5zM19 5h1v1h-1zM12 6h2v1h-2zM16 6h2v1h-2zM11 7h2v1h-2zM15 7h3v1h-3zM10 8h3v1h-3zM15 8h3v1h-3zM9 9h6v1h-6zM17 9h2v1h-2zM8 10h6v1h-6zM16 10h3v1h-3zM7 11h7v1h-7zM16 11h3v1h-3z",
    "4": "M14 6h2v1h-2zM13 7h2v1h-2zM13 8h2v1h-2zM15 9h2v1h-2zM14 10h2v1h-2zM14 11h2v1h-2z"
  },
  "CAP_WIDE": {
    "0": "M13 4h1v1h-1zM18 4h1v1h-1zM10 5h1v1h-1zM21 5h1v1h-1zM7 6h1v1h-1zM24 6h1v1h-1zM5 7h1v1h-1zM26 7h1v1h-1zM3 8h1v1h-1zM28 8h1v1h-1zM3 9h1v1h-1zM28 9h1v1h-1zM3 10h1v1h-1zM28 10h1v1h-1zM6 11h20v1h-20z",
    "1": "M20 5h1v1h-1zM23 6h1v1h-1zM24 7h2v1h-2zM26 8h2v1h-2zM26 9h2v1h-2zM4 10h24v1h-24z",
    "2": "M19 5h1v1h-1zM21 6h2v1h-2zM21 7h3v1h-3zM21 8h5v1h-5zM20 9h6v1h-6z",
    "3": "M14 4h4v1h-4zM11 5h5v1h-5zM18 5h1v1h-1zM8 6h6v1h-6zM18 6h3v1h-3zM6 7h7v1h-7zM17 7h4v1h-4zM4 8h8v1h-8zM16 8h5v1h-5zM4 9h16v1h-16z",
    "4": "M16 5h2v1h-2zM14 6h4v1h-4zM13 7h4v1h-4zM12 8h4v1h-4z"
  },
  "WEAPON_PITCHFORK": {
    "0": "M24 3h1v1h-1zM27 3h1v1h-1zM30 3h1v1h-1zM24 8h1v1h-1zM30 8h1v1h-1zM25 9h1v1h-1zM28 9h1v1h-1zM25 10h1v1h-1zM28 10h1v1h-1zM25 11h1v1h-1zM28 11h1v1h-1zM25 12h1v1h-1zM28 12h1v1h-1zM25 13h1v1h-1zM28 13h1v1h-1zM25 14h1v1h-1zM28 14h1v1h-1zM25 15h1v1h-1zM28 15h1v1h-1zM25 16h1v1h-1zM28 16h1v1h-1zM25 17h1v1h-1zM28 17h1v1h-1zM25 18h1v1h-1zM28 18h1v1h-1zM25 19h1v1h-1zM28 19h1v1h-1zM25 20h1v1h-1zM28 20h1v1h-1zM25 21h1v1h-1zM28 21h1v1h-1zM25 22h1v1h-1zM28 22h1v1h-1zM25 23h1v1h-1zM28 23h1v1h-1zM25 24h1v1h-1zM28 24h1v1h-1zM25 25h1v1h-1zM28 25h1v1h-1zM25 26h1v1h-1zM28 26h1v1h-1zM25 27h1v1h-1zM28 27h1v1h-1zM25 28h1v1h-1zM28 28h1v1h-1zM25 29h4v1h-4z",
    "1": "M27 9h1v1h-1zM27 10h1v1h-1zM27 11h1v1h-1zM27 12h1v1h-1zM27 13h1v1h-1zM27 14h1v1h-1zM27 15h1v1h-1zM27 16h1v1h-1zM27 17h1v1h-1zM27 18h1v1h-1zM27 19h1v1h-1zM27 20h1v1h-1zM27 21h1v1h-1zM27 22h1v1h-1zM27 23h1v1h-1zM27 24h1v1h-1zM27 25h1v1h-1zM27 26h1v1h-1zM27 27h1v1h-1zM27 28h1v1h-1z",
    "2": "M26 9h1v1h-1zM26 10h1v1h-1zM26 11h1v1h-1zM26 12h1v1h-1zM26 13h1v1h-1zM26 14h1v1h-1zM26 15h1v1h-1zM26 16h1v1h-1zM26 17h1v1h-1zM26 18h1v1h-1zM26 19h1v1h-1zM26 20h1v1h-1zM26 21h1v1h-1zM26 22h1v1h-1zM26 23h1v1h-1zM26 24h1v1h-1zM26 25h1v1h-1zM26 26h1v1h-1zM26 27h1v1h-1zM26 28h1v1h-1z",
    "3": "M25 8h5v1h-5z",
    "4": "M24 4h1v1h-1zM27 4h1v1h-1zM30 4h1v1h-1zM24 5h1v1h-1zM27 5h1v1h-1zM30 5h1v1h-1zM24 6h1v1h-1zM27 6h1v1h-1zM30 6h1v1h-1zM24 7h7v1h-7z"
  },
  "WEAPON_SHOVEL": {
    "0": "M25 6h4v1h-4zM25 7h1v1h-1zM28 7h1v1h-1zM25 8h1v1h-1zM28 8h1v1h-1zM25 9h1v1h-1zM28 9h1v1h-1zM25 10h1v1h-1zM28 10h1v1h-1zM25 11h1v1h-1zM28 11h1v1h-1zM25 12h1v1h-1zM28 12h1v1h-1zM25 13h1v1h-1zM28 13h1v1h-1zM25 14h1v1h-1zM28 14h1v1h-1zM25 15h1v1h-1zM28 15h1v1h-1zM25 16h1v1h-1zM28 16h1v1h-1zM25 17h1v1h-1zM28 17h1v1h-1zM25 18h1v1h-1zM28 18h1v1h-1zM25 19h1v1h-1zM28 19h1v1h-1zM25 20h1v1h-1zM28 20h1v1h-1zM25 21h1v1h-1zM28 21h1v1h-1zM25 22h1v1h-1zM28 22h1v1h-1zM25 23h1v1h-1zM28 23h1v1h-1zM25 24h1v1h-1zM28 24h1v1h-1zM25 25h1v1h-1zM28 25h1v1h-1zM23 26h8v1h-8zM23 27h1v1h-1zM30 27h1v1h-1zM23 28h1v1h-1zM30 28h1v1h-1zM24 29h1v1h-1zM29 29h1v1h-1zM25 30h4v1h-4z",
    "1": "M27 7h1v1h-1zM27 8h1v1h-1zM27 9h1v1h-1zM27 10h1v1h-1zM27 11h1v1h-1zM27 12h1v1h-1zM27 13h1v1h-1zM27 14h1v1h-1zM27 15h1v1h-1zM27 16h1v1h-1zM27 17h1v1h-1zM27 18h1v1h-1zM27 19h1v1h-1zM27 20h1v1h-1zM27 21h1v1h-1zM27 22h1v1h-1zM27 23h1v1h-1zM27 24h1v1h-1zM27 25h1v1h-1z",
    "2": "M26 7h1v1h-1zM26 8h1v1h-1zM26 9h1v1h-1zM26 10h1v1h-1zM26 11h1v1h-1zM26 12h1v1h-1zM26 13h1v1h-1zM26 14h1v1h-1zM26 15h1v1h-1zM26 16h1v1h-1zM26 17h1v1h-1zM26 18h1v1h-1zM26 19h1v1h-1zM26 20h1v1h-1zM26 21h1v1h-1zM26 22h1v1h-1zM26 23h1v1h-1zM26 24h1v1h-1zM26 25h1v1h-1z",
    "3": "M27 27h3v1h-3zM27 28h3v1h-3zM25 29h4v1h-4z",
    "4": "M24 27h3v1h-3zM24 28h3v1h-3z"
  },
  "WEAPON_STAFF": {
    "0": "M26 2h2v1h-2zM25 3h1v1h-1zM28 3h1v1h-1zM24 4h1v1h-1zM29 4h1v1h-1zM24 5h1v1h-1zM29 5h1v1h-1zM24 6h2v1h-2zM28 6h2v1h-2zM25 7h1v1h-1zM28 7h1v1h-1zM25 8h1v1h-1zM28 8h1v1h-1zM25 9h1v1h-1zM28 9h1v1h-1zM25 10h1v1h-1zM28 10h1v1h-1zM25 11h1v1h-1zM28 11h1v1h-1zM25 12h1v1h-1zM28 12h1v1h-1zM25 13h1v1h-1zM28 13h1v1h-1zM25 14h1v1h-1zM28 14h1v1h-1zM25 15h1v1h-1zM28 15h1v1h-1zM25 16h1v1h-1zM28 16h1v1h-1zM25 17h1v1h-1zM28 17h1v1h-1zM25 18h1v1h-1zM28 18h1v1h-1zM25 19h1v1h-1zM28 19h1v1h-1zM25 20h1v1h-1zM28 20h1v1h-1zM25 21h1v1h-1zM28 21h1v1h-1zM25 22h1v1h-1zM28 22h1v1h-1zM25 23h1v1h-1zM28 23h1v1h-1zM25 24h1v1h-1zM28 24h1v1h-1zM25 25h1v1h-1zM28 25h1v1h-1zM25 26h1v1h-1zM28 26h1v1h-1zM25 27h1v1h-1zM28 27h1v1h-1zM25 28h1v1h-1zM28 28h1v1h-1zM25 29h1v1h-1zM28 29h1v1h-1zM25 30h4v1h-4z",
    "1": "M27 8h1v1h-1zM27 9h1v1h-1zM27 10h1v1h-1zM27 11h1v1h-1zM27 12h1v1h-1zM27 13h1v1h-1zM27 14h1v1h-1zM27 15h1v1h-1zM27 16h1v1h-1zM27 17h1v1h-1zM27 18h1v1h-1zM27 19h1v1h-1zM27 20h1v1h-1zM27 21h1v1h-1zM27 22h1v1h-1zM27 23h1v1h-1zM27 24h1v1h-1zM27 25h1v1h-1zM27 26h1v1h-1zM27 27h1v1h-1zM27 28h1v1h-1zM27 29h1v1h-1z",
    "2": "M26 8h1v1h-1zM26 9h1v1h-1zM26 10h1v1h-1zM26 11h1v1h-1zM26 12h1v1h-1zM26 13h1v1h-1zM26 14h1v1h-1zM26 15h1v1h-1zM26 16h1v1h-1zM26 17h1v1h-1zM26 18h1v1h-1zM26 19h1v1h-1zM26 20h1v1h-1zM26 21h1v1h-1zM26 22h1v1h-1zM26 23h1v1h-1zM26 24h1v1h-1zM26 25h1v1h-1zM26 26h1v1h-1zM26 27h1v1h-1zM26 28h1v1h-1zM26 29h1v1h-1z",
    "3": "M26 5h2v1h-2zM26 7h2v1h-2z",
    "4": "M26 3h2v1h-2zM25 4h4v1h-4zM25 5h1v1h-1zM28 5h1v1h-1zM26 6h2v1h-2z"
  }
};
